from __future__ import annotations

from typing import Protocol

import pandas as pd


class TargetGenerator(Protocol):
    name: str

    def generate_entry_labels(self, df: pd.DataFrame) -> pd.Series:
        """Return labels aligned with df index."""

    def generate_exit_labels(
        self,
        df: pd.DataFrame,
        forward_window: int,
        loss_threshold: float,
    ) -> pd.Series | None:
        """Return binary exit labels or None if unsupported."""

    @property
    def num_classes(self) -> int:
        """Number of classes generated by entry labels."""

    @property
    def supports_exit_labels(self) -> bool:
        """Whether this generator supports exit labels."""
