"""
Export V24 trades for web visualization (data_v24/{SYM}.json).
Input source: results/trades_v24.csv generated by run_v24.py.
"""
import json
import os
from datetime import datetime

import numpy as np
import pandas as pd


COLORS = {"v24": "#FFD54F"}


def make_markers(trades):
    markers = []
    buy_color = COLORS["v24"]
    win_color, loss_color = "#4caf50", "#f44336"

    short = {
        "stop_loss": "SL",
        "trailing_stop": "TS",
        "hard_stop": "HS",
        "zombie_exit": "ZE",
        "hybrid_exit": "HX",
        "profit_lock": "PL",
        "profit_floor": "PF",
        "peak_protect_dist": "PP",
        "peak_protect_ema": "PE",
        "fast_loss_cut": "FC",
        "fast_exit_loss": "FE",
        "signal_hard_cap": "HC",
        "signal": "",
        "end": "END",
    }

    for t in trades:
        ed, xd = t.get("entry_date", ""), t.get("exit_date", "")
        pnl = float(t.get("pnl_pct", 0))
        reason = t.get("exit_reason", "")
        tag = short.get(reason, reason[:2].upper() if reason else "")
        if ed:
            markers.append(
                {
                    "time": ed,
                    "position": "belowBar",
                    "color": buy_color,
                    "shape": "arrowUp",
                    "text": "V24 Buy",
                    "size": 1,
                    "method": "v24",
                }
            )
        if xd:
            markers.append(
                {
                    "time": xd,
                    "position": "aboveBar",
                    "color": win_color if pnl >= 0 else loss_color,
                    "shape": "arrowDown",
                    "text": f"V24 {pnl:+.1f}%{(' ' + tag) if tag else ''}",
                    "size": 1,
                    "method": "v24",
                }
            )
    return markers


def compute_stats(trades):
    if not trades:
        return {
            "total_trades": 0,
            "wins": 0,
            "losses": 0,
            "win_rate": 0,
            "total_pnl_pct": 0,
            "avg_pnl_pct": 0,
            "avg_hold": 0,
            "pf": 0,
            "version": "V24",
        }

    pnls = [float(t["pnl_pct"]) for t in trades]
    wins = [p for p in pnls if p > 0]
    losses = [p for p in pnls if p <= 0]
    holds = [float(t.get("holding_days", 0)) for t in trades]
    gross_loss = abs(sum(losses))
    avg_win = float(np.mean(wins)) if wins else 0.0
    avg_loss = float(np.mean(losses)) if losses else 0.0
    payoff_ratio = (avg_win / abs(avg_loss)) if avg_loss < 0 else 0.0
    return {
        "total_trades": len(trades),
        "wins": len(wins),
        "losses": len(losses),
        "win_rate": round(len(wins) / len(trades) * 100, 1),
        "total_pnl_pct": round(sum(pnls), 1),
        "avg_pnl_pct": round(float(np.mean(pnls)), 2),
        "median_pnl_pct": round(float(np.median(pnls)), 2),
        "std_pnl_pct": round(float(np.std(pnls)), 2),
        "avg_win_pct": round(avg_win, 2),
        "avg_loss_pct": round(avg_loss, 2),
        "payoff_ratio": round(payoff_ratio, 2),
        "max_win_pct": round(float(max(pnls)), 2),
        "max_loss_pct": round(float(min(pnls)), 2),
        "avg_hold": round(float(np.mean(holds)), 1) if holds else 0,
        "pf": round(sum(wins) / gross_loss, 2) if gross_loss > 0 else 99,
        "version": "V24",
    }


def select_fields(df):
    fields = (
        "entry_date",
        "exit_date",
        "pnl_pct",
        "holding_days",
        "exit_reason",
        "entry_trend",
        "quick_reentry",
        "breakout_entry",
        "vshape_entry",
        "entry_profile",
        "entry_choppy_regime",
        "position_size",
    )
    out = []
    for row in df.to_dict("records"):
        clean = {}
        for key in fields:
            if key not in row:
                continue
            val = row[key]
            if pd.isna(val):
                continue
            if isinstance(val, (np.generic,)):
                val = val.item()
            clean[key] = val
        out.append(clean)
    return out


def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    trades_csv = os.path.join(base_dir, "results", "trades_v24.csv")
    out_dir = os.path.join(base_dir, "visualization", "data_v24")
    os.makedirs(out_dir, exist_ok=True)

    if not os.path.exists(trades_csv):
        raise FileNotFoundError(f"Missing file: {trades_csv}. Run python stock_ml/run_v24.py first.")

    df = pd.read_csv(trades_csv)
    if "symbol" not in df.columns:
        if "entry_symbol" in df.columns:
            df["symbol"] = df["entry_symbol"].astype(str)
        else:
            raise ValueError("trades_v24.csv has no symbol column")

    for c in ("entry_date", "exit_date"):
        if c in df.columns:
            df[c] = df[c].astype(str).str[:10]

    base_index_path = os.path.join(base_dir, "visualization", "data", "index.json")
    base_symbols = []
    if os.path.exists(base_index_path):
        with open(base_index_path, "r", encoding="utf-8") as f:
            base_index = json.load(f)
        base_symbols = [row.get("symbol") for row in base_index.get("symbols", []) if row.get("symbol")]

    symbols_from_trades = sorted(df["symbol"].dropna().astype(str).unique().tolist())
    if base_symbols:
        ordered = []
        seen = set()
        for sym in base_symbols + symbols_from_trades:
            if sym in seen:
                continue
            seen.add(sym)
            ordered.append(sym)
        export_symbols = ordered
    else:
        export_symbols = symbols_from_trades

    grouped = {sym: g.copy().sort_values(["entry_date", "exit_date"]).reset_index(drop=True)
               for sym, g in df.groupby("symbol")}

    index_entries = []
    for symbol in export_symbols:
        sym_df = grouped.get(symbol, pd.DataFrame())
        trades = select_fields(sym_df) if len(sym_df) > 0 else []
        stats = compute_stats(trades)
        payload = {
            "symbol": symbol,
            "v24_markers": make_markers(trades),
            "v24_trades": trades,
            "v24_stats": stats,
        }
        with open(os.path.join(out_dir, f"{symbol}.json"), "w", encoding="utf-8") as f:
            json.dump(payload, f, ensure_ascii=False)
        index_entries.append(
            {
                "symbol": symbol,
                "v24_trades": stats["total_trades"],
                "v24_pnl": stats["total_pnl_pct"],
                "v24_wr": stats["win_rate"],
            }
        )

    index_entries.sort(key=lambda x: x["v24_pnl"], reverse=True)
    with open(os.path.join(out_dir, "index.json"), "w", encoding="utf-8") as f:
        json.dump(
            {
                "symbols": index_entries,
                "version": "V24",
                "generated_at": datetime.now().isoformat(),
            },
            f,
            indent=2,
            ensure_ascii=False,
        )

    total = sum(row["v24_pnl"] for row in index_entries)
    with_trades = sum(1 for row in index_entries if row["v24_trades"] > 0)
    print(f"Exported {len(index_entries)} symbols to {out_dir}")
    print(f"Symbols with V24 trades: {with_trades}/{len(index_entries)}")
    print(f"V24 aggregate PnL: {total:+.1f}%")


if __name__ == "__main__":
    main()
