import psycopg2
con = psycopg2.connect(host="localhost", port=5433, dbname="stockml", user="stockml", password="stockml_dev")
cur = con.cursor()
cur.execute("SELECT column_name FROM information_schema.columns WHERE table_name='universe_symbols' ORDER BY ordinal_position")
print([r[0] for r in cur.fetchall()])
cur.execute("SELECT column_name FROM information_schema.columns WHERE table_name='universe_versions' ORDER BY ordinal_position")
print([r[0] for r in cur.fetchall()])
cur.execute("SELECT * FROM universe_versions LIMIT 5")
for r in cur.fetchall(): print(r)
con.close()
